# Generated by Django 4.1.7 on 2023-07-12 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.FloatField(blank=True, default=0, null=True, verbose_name='Остаток занятий')),
            ],
            options={
                'verbose_name': 'Учетная запись',
                'verbose_name_plural': 'Учетные записи',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Фото')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='Почта')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Номер телефона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж в танго')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trainers/', verbose_name='фото')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='Почта')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Номер телефона')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='фото')),
                ('level', models.CharField(blank=True, choices=[('Продолжающий', 'advanced'), ('Начинающий', 'beginner')], max_length=30, null=True, verbose_name='Уровень подготовки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('student_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tangoschool.account')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['-is_active', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('buying', 'Покупка'), ('visiting', 'Посещение')], max_length=10, verbose_name='Операция с балансом')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата операции')),
                ('amount', models.FloatField(default=1, verbose_name='количество за раз')),
                ('lesson_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='tangoschool.account')),
            ],
            options={
                'verbose_name': 'Операция с балансом',
                'verbose_name_plural': 'Операции с балансом',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_topic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тема занятия')),
                ('lesson_type', models.CharField(choices=[('full', 'Полное занятие'), ('practice', 'Практика')], max_length=10)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата занятия')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время занятия')),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Начинающий'), ('advanced', 'Продолжающий')], max_length=30, null=True, verbose_name='Уровень сложности')),
                ('guests_total_money', models.IntegerField(blank=True, default=0, verbose_name='Сумма от гостей')),
                ('guests', models.ManyToManyField(blank=True, to='tangoschool.guest', verbose_name='Список гостей, записанных на занятие')),
                ('students', models.ManyToManyField(blank=True, to='tangoschool.student', verbose_name='Список учеников, записанных на занятие')),
                ('trainer1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons_as_trainer1', to='tangoschool.trainerprofile', verbose_name='Тренер 1')),
                ('trainer2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons_as_trainer2', to='tangoschool.trainerprofile', verbose_name='Тренер 2')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
                'ordering': ['date', 'time', 'trainer1', 'trainer2'],
            },
        ),
    ]
