# Generated by Django 4.1.7 on 2023-05-16 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tangoschool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='base_amount',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_topic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Описание занятия'),
        ),
        migrations.CreateModel(
            name='LessonParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tangoschool.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tangoschool.student')),
            ],
        ),
    ]
