# Generated by Django 4.1.7 on 2023-07-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangoschool', '0004_alter_operation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Начинающий'), ('advanced', 'Продолжающий')], max_length=30, null=True, verbose_name='Уровень подготовки'),
        ),
    ]
