# Generated by Django 4.1.7 on 2023-08-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangoschool', '0007_alter_operation_date_alter_operation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='Почта'),
        ),
    ]
