# Generated by Django 4.1.7 on 2023-09-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangoschool', '0008_alter_trainerprofile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-is_active', 'level', 'last_name'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(verbose_name='Дата занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(verbose_name='Время занятия'),
        ),
    ]
