# Generated by Django 4.1.7 on 2024-05-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangoschool', '0009_alter_student_options_alter_lesson_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Обліковий запис', 'verbose_name_plural': 'Облікові записи'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Гість', 'verbose_name_plural': 'Гості'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Операція з балансом', 'verbose_name_plural': 'Операції з балансом'},
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Залишок занять'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(verbose_name='Дата заняття'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='guests',
            field=models.ManyToManyField(blank=True, to='tangoschool.guest', verbose_name='Список гостей, записанных на заняття'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='guests_total_money',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма від гостей'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_topic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тема заняття'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('full', 'Повне заняття'), ('practice', 'Практика')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Початковий'), ('advanced', 'Продовжуючий')], max_length=30, null=True, verbose_name='Рівень складності'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(blank=True, to='tangoschool.student', verbose_name='Список учнів, записанных на заняття'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(verbose_name='Время заняття'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='День народження'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, verbose_name='Пошта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус активності'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Початковий'), ('advanced', 'Продовжуючий')], max_length=30, null=True, verbose_name='Рівень підготовки'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='День народження'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='Пошта'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Номер телефону'),
        ),
    ]
